apiVersion: apps/v1
kind: Deployment
metadata:
  name: rearc-webapp
  namespace: rearc
spec:
  selector:
    matchLabels:
      run: rearc-webapp
  replicas: 3
  template:
    metadata:
      labels:
        run: rearc-webapp
    spec:
      containers:
        - name: rearc-webapp
          image: default:latest
          ports:
            - containerPort: 3000
          env:
            - name: SECRET_WORD
              valueFrom:
                secretKeyRef:
                  name: rearc-secret
                  key: SECRET_WORD
